### ISSUE TITLE
不支持 m1 pro macbook pro

### ISSUE THREAD

**Issue by yym68686** [libAudioFlux/audioFlux#12]
用pip install audioflux 安装后运行报错：

```
Traceback (most recent call last):
  File "/Users/***/Downloads/GitHub/AudioAnalysis/test.py", line 1, in <module>
    import audioflux as af
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/__init__.py", line 1, in <module>
    from .bft import *
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/bft.py", line 5, in <module>
    from audioflux.base import Base
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/base.py", line 1, in <module>
    from audioflux.fftlib import get_fft_lib
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/fftlib.py", line 129, in <module>
    set_fft_lib(None)
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/fftlib.py", line 125, in set_fft_lib
    __LIBRARY['_lib'] = load_library(lib_fp)
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/Users/***/opt/anaconda3/envs/audio/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/lib/libaudioflux.dylib, 0x0006): tried: '/Users/***/opt/anaconda3/envs/audio/lib/python3.9/site-packages/audioflux/lib/libaudioflux.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by wtq2255** [comment]
我们会在下个版本增加对mac arm的支持，你可以先使用这个测试版本 [audioflux-0.1.3-py3-none-any.whl.zip](https://github.com/libAudioFlux/audioFlux/files/11008498/audioflux-0.1.3-py3-none-any.whl.zip)
使用pip本地安装 `pip install path/audioflux-0.1.3-py3-none-any.whl`
