### ISSUE TITLE
python无法加载audioflux 模块

### ISSUE THREAD

**Issue by chentaoabc** [libAudioFlux/audioFlux#6]
你好，我在python中使用pip install audioflux来安装，之后使用import audioflux as af来导入该模块，但是出现了[WinError 126] 找不到指定的模块。

**Comment by wtq2255** [comment]
@chentaoabc 请提供一下 系统版本信息 / python版本信息 / 错误堆栈信息吧

**Comment by chentaoabc** [comment]
windows, python==3.7.3, 
错误问题：
E:\Anaconda\python.exe E:/ct/小波变换数据增强/ST_IQ.py
Traceback (most recent call last):
  File "E:/ct/小波变换数据增强/ST_IQ.py", line 2, in <module>
    import audioflux as af
  File "E:\Anaconda\lib\site-packages\audioflux\__init__.py", line 1, in <module>
    from .bft import *
  File "E:\Anaconda\lib\site-packages\audioflux\bft.py", line 5, in <module>
    from audioflux.base import Base
  File "E:\Anaconda\lib\site-packages\audioflux\base.py", line 1, in <module>
    from audioflux.fftlib import get_fft_lib
  File "E:\Anaconda\lib\site-packages\audioflux\fftlib.py", line 121, in <module>
    set_fft_lib(None)
  File "E:\Anaconda\lib\site-packages\audioflux\fftlib.py", line 117, in set_fft_lib
    __LIBRARY['_lib'] = load_library(lib_fp)
  File "E:\Anaconda\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "E:\Anaconda\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by wtq2255** [comment]
@chentaoabc windows系统版本是win7/win10/win11呢？

**Comment by chentaoabc** [comment]
win11

**Comment by wtq2255** [comment]
你可以试一下这个测试版本 [audioflux-0.1.2-py3-none-any.whl.zip](https://github.com/libAudioFlux/audioFlux/files/10900387/audioflux-0.1.2-py3-none-any.whl.zip)
使用pip本地安装 `pip install path/audioflux-0.1.2-py3-none-any.whl`

**Comment by chentaoabc** [comment]
可以导入使用了，非常感谢啊

**Comment by wtq2255** [comment]
@chentaoabc 好的，我们后续会发一个新版本解决这个问题
